"""Add computation scripts table

Revision ID: 3df9c4652156
Revises: ac9f3dbd0130
Create Date: 2026-01-09 12:24:27.801130

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "3df9c4652156"
down_revision = "ac9f3dbd0130"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to ignore legacy tables ###
    op.create_table(
        "computation_scripts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("uploaded_by", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_by", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_by", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("metadata_json", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("computation_scripts_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("computation_scripts_pkey")),
    )
    op.create_index(
        op.f("ix_computation_scripts_id"), "computation_scripts", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_computation_scripts_id"), table_name="computation_scripts")
    op.drop_table("computation_scripts")
    # ### end Alembic commands ###
