"""initial_schema_water_dp

Revision ID: d89d8f0ea294
Revises:
Create Date: 2026-02-01 12:17:45.618475

"""

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "d89d8f0ea294"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geo_layers",
        sa.Column("layer_name", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("workspace", sa.String(length=50), nullable=False),
        sa.Column("store_name", sa.String(length=100), nullable=False),
        sa.Column("srs", sa.String(length=20), nullable=False),
        sa.Column("layer_type", sa.String(length=50), nullable=False),
        sa.Column("geometry_type", sa.String(length=20), nullable=True),
        sa.Column("style_name", sa.String(length=100), nullable=True),
        sa.Column("data_source", sa.String(length=200), nullable=True),
        sa.Column("data_format", sa.String(length=20), nullable=True),
        sa.Column("is_published", sa.String(length=10), nullable=True),
        sa.Column("is_public", sa.String(length=10), nullable=True),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "style_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_layer_published", "geo_layers", ["is_published"], unique=False)
    op.create_index("idx_layer_type", "geo_layers", ["layer_type"], unique=False)
    op.create_index("idx_layer_workspace", "geo_layers", ["workspace"], unique=False)
    op.create_index(op.f("ix_geo_layers_id"), "geo_layers", ["id"], unique=False)
    op.create_index(
        op.f("ix_geo_layers_layer_name"), "geo_layers", ["layer_name"], unique=True
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "authorization_provider_group_id", sa.String(length=255), nullable=True
        ),
        sa.Column("schema_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="water_dp",
    )
    op.create_index(
        op.f("ix_water_dp_projects_authorization_provider_group_id"),
        "projects",
        ["authorization_provider_group_id"],
        unique=False,
        schema="water_dp",
    )
    op.create_index(
        op.f("ix_water_dp_projects_id"),
        "projects",
        ["id"],
        unique=False,
        schema="water_dp",
    )
    op.create_index(
        op.f("ix_water_dp_projects_owner_id"),
        "projects",
        ["owner_id"],
        unique=False,
        schema="water_dp",
    )
    op.create_index(
        op.f("ix_water_dp_projects_schema_name"),
        "projects",
        ["schema_name"],
        unique=False,
        schema="water_dp",
    )
    op.create_table(
        "geo_features",
        sa.Column("layer_id", sa.String(length=100), nullable=False),
        sa.Column("feature_id", sa.String(length=100), nullable=False),
        sa.Column("feature_type", sa.String(length=50), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                srid=4326, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
            ),
            nullable=False,
        ),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("valid_from", sa.DateTime(), nullable=True),
        sa.Column("valid_to", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.String(length=10), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["layer_id"],
            ["geo_layers.layer_name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_feature_active", "geo_features", ["is_active"], unique=False)
    op.create_index(
        "idx_feature_geometry",
        "geo_features",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index("idx_feature_layer", "geo_features", ["layer_id"], unique=False)
    op.create_index("idx_feature_type", "geo_features", ["feature_type"], unique=False)
    op.create_index(
        "idx_feature_valid_from", "geo_features", ["valid_from"], unique=False
    )

    op.create_index(
        op.f("ix_geo_features_feature_id"), "geo_features", ["feature_id"], unique=False
    )
    op.create_index(op.f("ix_geo_features_id"), "geo_features", ["id"], unique=False)
    op.create_table(
        "project_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["water_dp.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "user_id", name="uq_project_member"),
    )
    op.create_index(
        op.f("ix_project_members_id"), "project_members", ["id"], unique=False
    )
    op.create_table(
        "project_sensors",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("thing_uuid", sa.UUID(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["water_dp.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id", "thing_uuid"),
    )
    op.create_table(
        "alert_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("alert_type", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=True),
        sa.Column(
            "conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("severity", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["water_dp.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="water_dp",
    )
    op.create_index(
        op.f("ix_water_dp_alert_definitions_id"),
        "alert_definitions",
        ["id"],
        unique=False,
        schema="water_dp",
    )
    op.create_table(
        "computation_scripts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["water_dp.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="water_dp",
    )
    op.create_index(
        op.f("ix_water_dp_computation_scripts_id"),
        "computation_scripts",
        ["id"],
        unique=False,
        schema="water_dp",
    )
    op.create_table(
        "dashboards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "layout_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("widgets", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["water_dp.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="water_dp",
    )
    op.create_index(
        op.f("ix_water_dp_dashboards_id"),
        "dashboards",
        ["id"],
        unique=False,
        schema="water_dp",
    )
    op.create_table(
        "datasources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column(
            "connection_details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["water_dp.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="water_dp",
    )
    op.create_index(
        op.f("ix_water_dp_datasources_id"),
        "datasources",
        ["id"],
        unique=False,
        schema="water_dp",
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("definition_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("acknowledged_by", sa.String(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["definition_id"], ["water_dp.alert_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="water_dp",
    )
    op.create_index(
        op.f("ix_water_dp_alerts_id"), "alerts", ["id"], unique=False, schema="water_dp"
    )
    op.create_table(
        "computation_jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("script_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("start_time", sa.String(), nullable=True),
        sa.Column("end_time", sa.String(), nullable=True),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("logs", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["script_id"], ["water_dp.computation_scripts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="water_dp",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flyway_schema_history",
        sa.Column("installed_rank", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("version", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "description", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.Column("type", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "script", sa.VARCHAR(length=1000), autoincrement=False, nullable=False
        ),
        sa.Column("checksum", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "installed_by", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "installed_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("execution_time", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("success", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint(
            "installed_rank", name=op.f("flyway_schema_history_pk")
        ),
    )
    op.create_index(
        op.f("flyway_schema_history_s_idx"),
        "flyway_schema_history",
        ["success"],
        unique=False,
    )
    op.create_table(
        "configuration_static_location_begin_action",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "configuration_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "begin_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("begin_description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "begin_contact_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "x", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "y", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "z", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "epsg_code", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "elevation_datum_name",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "elevation_datum_uri",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("end_description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("end_contact_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("label", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("configuration_static_location_begin_action_pkey")
        ),
    )
    op.create_table(
        "configuration_contact_role",
        sa.Column("role_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "role_uri", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("contact_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "configuration_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("configuration_contact_role_pkey")),
    )
    op.create_table(
        "license",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("term", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "provenance_uri", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("provenance", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("definition", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "contact",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "given_name", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "family_name", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "website", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "organization", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
        sa.Column("orcid", sa.VARCHAR(length=32), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("contact_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("contact_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "orcid",
            name=op.f("contact_orcid_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "device_contact_role",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "role_uri", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "role_name", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column("contact_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("device_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("device_contact_role_pkey")),
    )
    op.create_table(
        "configuration_dynamic_location_begin_action",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "configuration_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "begin_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("begin_description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "begin_contact_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("x_property_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("y_property_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("z_property_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "epsg_code", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "elevation_datum_name",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "elevation_datum_uri",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("end_description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("end_contact_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("label", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("configuration_dynamic_location_begin_action_pkey")
        ),
    )
    op.create_table(
        "alembic_version",
        sa.Column(
            "version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
    )
    op.create_table(
        "datastream_link",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "device_property_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "device_mount_action_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "datasource_id", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "thing_id", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "datastream_id", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "begin_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "datasource_name",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "thing_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "datastream_name",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "license_uri", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "license_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "aggregation_period",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("tsm_endpoint_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("datastream_link_pkey")),
    )
    op.create_table(
        "measured_quantity",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("term", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "provenance_uri", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("definition", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("measured_quantity_pkey")),
    )
    op.create_table(
        "aggregation_type",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("term", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("definition", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "device",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "short_name", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "long_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "serial_number", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "manufacturer_uri",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "manufacturer_name",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("dual_use", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("model", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column(
            "inventory_number",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "persistent_identifier",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "website", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
        sa.Column(
            "device_type_uri",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "device_type_name",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status_uri", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "status_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "group_ids",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_private", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_internal", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_public", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "update_description",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("archived", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "identifier_type",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "schema_version", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("device_pkey")),
        sa.UniqueConstraint(
            "persistent_identifier",
            name=op.f("device_persistent_identifier_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "device_mount_action",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "configuration_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("device_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "parent_platform_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "begin_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("begin_description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "begin_contact_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "offset_x",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "offset_y",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "offset_z",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("end_description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("end_contact_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("label", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("device_mount_action_pkey")),
    )
    op.create_table(
        "schema_thing_mapping",
        sa.Column(
            "schema", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("thing_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.UniqueConstraint(
            "schema",
            "thing_uuid",
            name=op.f("schema_thing_mapping_schema_thing_uuid_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "configuration",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "start_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("label", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column(
            "cfg_permission_group", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("is_internal", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_public", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "update_description",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("archived", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("site_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "project", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "persistent_identifier",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("configuration_pkey")),
        sa.UniqueConstraint(
            "persistent_identifier",
            name=op.f("configuration_persistent_identifier_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
        ),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    op.create_table(
        "unit",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("term", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("definition", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("provenance", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "device_property",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "measuring_range_min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "measuring_range_max",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "failure_value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "accuracy",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("label", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column(
            "unit_uri", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "unit_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "compartment_uri",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "compartment_name",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "property_uri", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "property_name", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "sampling_media_uri",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "sampling_media_name",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("device_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "resolution",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "resolution_unit_name",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "resolution_unit_uri",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "aggregation_type_uri",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "aggregation_type_name",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "accuracy_unit_name",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "accuracy_unit_uri",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("device_property_pkey")),
    )
    op.drop_table("computation_jobs", schema="water_dp")
    op.drop_index(op.f("ix_water_dp_alerts_id"), table_name="alerts", schema="water_dp")
    op.drop_table("alerts", schema="water_dp")
    op.drop_index(
        op.f("ix_water_dp_datasources_id"), table_name="datasources", schema="water_dp"
    )
    op.drop_table("datasources", schema="water_dp")
    op.drop_index(
        op.f("ix_water_dp_dashboards_id"), table_name="dashboards", schema="water_dp"
    )
    op.drop_table("dashboards", schema="water_dp")
    op.drop_index(
        op.f("ix_water_dp_computation_scripts_id"),
        table_name="computation_scripts",
        schema="water_dp",
    )
    op.drop_table("computation_scripts", schema="water_dp")
    op.drop_index(
        op.f("ix_water_dp_alert_definitions_id"),
        table_name="alert_definitions",
        schema="water_dp",
    )
    op.drop_table("alert_definitions", schema="water_dp")
    op.drop_table("project_sensors")
    op.drop_index(op.f("ix_project_members_id"), table_name="project_members")
    op.drop_table("project_members")
    op.drop_index(op.f("ix_geo_features_id"), table_name="geo_features")
    op.drop_index(op.f("ix_geo_features_feature_id"), table_name="geo_features")
    op.drop_index(
        "idx_geo_features_geometry", table_name="geo_features", postgresql_using="gist"
    )
    op.drop_index("idx_feature_valid_from", table_name="geo_features")
    op.drop_index("idx_feature_type", table_name="geo_features")
    op.drop_index("idx_feature_layer", table_name="geo_features")
    op.drop_index(
        "idx_feature_geometry", table_name="geo_features", postgresql_using="gist"
    )
    op.drop_index("idx_feature_active", table_name="geo_features")
    op.drop_table("geo_features")
    op.drop_index(
        op.f("ix_water_dp_projects_schema_name"),
        table_name="projects",
        schema="water_dp",
    )
    op.drop_index(
        op.f("ix_water_dp_projects_owner_id"), table_name="projects", schema="water_dp"
    )
    op.drop_index(
        op.f("ix_water_dp_projects_id"), table_name="projects", schema="water_dp"
    )
    op.drop_index(
        op.f("ix_water_dp_projects_authorization_provider_group_id"),
        table_name="projects",
        schema="water_dp",
    )
    op.drop_table("projects", schema="water_dp")
    op.drop_index(op.f("ix_geo_layers_layer_name"), table_name="geo_layers")
    op.drop_index(op.f("ix_geo_layers_id"), table_name="geo_layers")
    op.drop_index("idx_layer_workspace", table_name="geo_layers")
    op.drop_index("idx_layer_type", table_name="geo_layers")
    op.drop_index("idx_layer_published", table_name="geo_layers")
    op.drop_table("geo_layers")
    # ### end Alembic commands ###
