"""add_schema_name_to_projects

Revision ID: f59aaac0d928
Revises: 475f93023348
Create Date: 2026-01-28 01:36:17.425531

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f59aaac0d928'
down_revision = '475f93023348'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('schema_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_projects_schema_name'), 'projects', ['schema_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_schema_name'), table_name='projects')
    op.drop_column('projects', 'schema_name')
    # ### end Alembic commands ###
